### PR TITLE
You can run... but you can't hide.

### PR DESCRIPTION
**Pull request by ghost**
Also, I fixed your shoddy space indentation :-p.

### CODE REVIEW

**Review by nathanrw — CHANGES_REQUESTED** [review]
Looks good! I'll be happy to merge it in with the following changes:
1. pymunk is supposed to be encapsulated inside physics.py, but it's now leaking out (you're setting body.body.force in FollowsPlayer update() method.) I think this could be fixed by adding a "force" property to the Body class which wraps the pymunk "force" property - look at the other properties on the Body class for examples of how to do this.
2. The indentation style for this project is spaces and not tabs, so it should be spaces. Certainly mixing spaces and tabs in the same file is a bad idea, especially in Python. Python generally gets very upset when you mix tabs and spaces - whitespace is part of the syntax, and IIRC a tab is seen as equivalent to 8 spaces, and I've been using 4 space indentation. I think your tab-ified region happens to be working in this case because the whole class is tab-ified. But generally it's a bad idea.

Thanks for contributing!

**Comment by ghost** [comment]
OK. I guess I'll be writing a sed script to convert between indentation styles sooner rather than later (and getting stuck into branches in the process). I'll get on both points.

Any idea how I'd have the script in one branch but not another? I'll get stuck into the docs otherwise.

**Comment by nathanrw** [comment]
You could just keep the script in your home directory? 

Or just never commit it to a branch and tell git to ignore it?

Or just use Emacs and never worry about what indentation character is actually being used trollololol :p

**Comment by ghost** [comment]
All done. I got stuck on how I'd do the script in sed, but it turned out to be really easy with GNU coreutils:

``` bash
#!/bin/bash
if [ $1 = "-d" ] ;
        then for a in *py src/*py ; do mv $a ${a}.tmp ; unexpand --first-only -t4 ${a}.tmp >$a ; rm ${a}.tmp ; done ;
        else for a in *py src/*py ; do mv $a ${a}.tmp ; expand -it4 ${a}.tmp >$a ; rm ${a}.tmp ; done ;
fi

chmod a+x run.py
```

**Comment by nathanrw** [comment]
Just played it, the new behaviour is really good. Thanks!

**Pull request merged**
